name: ChunkLoader
main: org.kayteam.chunkloader.main.ChunkLoader
version: 2.2
author: segu23
commands:
  addchunk:
    description: AddChunk
    permission: chunkloader.addchunk
  removechunk:
    description: RemoveChunk
    permission: chunkloader.removechunk
  chunkloader:
    description: ChunkLoader
    permission: chunkloader.chunkloader
    aliases:
      - cl
      - cloader
      - chunkl
permissions:
  chunkloader.admin:
    children:
      chunkloader.addchunk: true
      chunkloader.removechunk: true
      chunkloader.chunkloader: true